name: rvfitter
channels:
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - astropy=5.0.4
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cycler=0.11.0
  - dbus=1.13.18
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.4.4
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - ipython=8.4.0
  - jedi=0.18.1
  - jpeg=9e
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libedit=3.1.20210910
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libpq=12.9
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.2
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - ply=3.11
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyerfa=2.0.0
  - pygments=2.11.2
  - pyparsing=3.0.4
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.9.12
  - python-dateutil=2.8.2
  - pytz=2022.1
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.1.2
  - scipy=1.7.3
  - setuptools=61.2.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.39.2
  - stack_data=0.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.1
  - traitlets=5.1.1
  - tzdata=2022a
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - asdf==2.12.0
    - asdf-astropy==0.2.1
    - asdf-coordinates-schemas==0.1.0
    - asdf-standard==1.0.3
    - asdf-transform-schemas==0.2.2
    - asdf-wcs-schemas==0.1.1
    - astroquery==0.4.6
    - attrs==22.1.0
    - beautifulsoup4==4.11.1
    - bokeh==2.4.3
    - cffi==1.15.1
    - charset-normalizer==2.1.0
    - click==8.1.3
    - cryptography==37.0.4
    - flask==2.2.2
    - gwcs==0.18.1
    - html5lib==1.1
    - idna==3.3
    - importlib-metadata==4.12.0
    - itsdangerous==2.1.2
    - jeepney==0.8.0
    - jinja2==3.1.2
    - jmespath==1.0.1
    - jsonschema==4.9.1
    - keyring==23.8.2
    - markupsafe==2.1.1
    - ndcube==2.0.2
    - pycparser==2.21
    - pyrsistent==0.18.1
    - pyvo==1.3
    - requests==2.28.1
    - secretstorage==3.3.2
    - semantic-version==2.10.0
    - soupsieve==2.3.2.post1
    - specutils==1.7.0
    - tqdm==4.64.0
    - typing-extensions==4.3.0
    - urllib3==1.26.11
    - webencodings==0.5.1
    - werkzeug==2.2.2
    - zipp==3.8.1
